config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :add_not_null_constraint_to_genres_names
  resources :subscriptions
  resources :subscribs
  resources :subscribtions
  resources :subscribers
  resources :books_authors
  resources :books_genres
  resources :books
  resources :authors
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/books_author.rb
# frozen_string_literal: true

class BooksAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
  validates :book, presence: true
  validates :author, presence: true
  validates :book, uniqueness: { scope: :author }
end

app/controllers/books_authors_controller.rb
# frozen_string_literal: true

class BooksAuthorsController < ApplicationController
  before_action :set_books_author, only: %i[show edit update destroy]

  # GET /books_authors or /books_authors.json
  def index
    @books_authors = BooksAuthor.all
  end

  # GET /books_authors/1 or /books_authors/1.json
  def show; end

  # GET /books_authors/new
  def new
    @books_author = BooksAuthor.new
  end

  # GET /books_authors/1/edit
  def edit; end

  # POST /books_authors or /books_authors.json
  def create
    @books_author = BooksAuthor.new(books_author_params)

    respond_to do |format|
      if @books_author.save
        format.html { redirect_to books_author_url(@books_author), notice: 'Books author was successfully created.' }
        format.json { render :show, status: :created, location: @books_author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @books_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books_authors/1 or /books_authors/1.json
  def update
    respond_to do |format|
      if @books_author.update(books_author_params)
        format.html { redirect_to books_author_url(@books_author), notice: 'Books author was successfully updated.' }
        format.json { render :show, status: :ok, location: @books_author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @books_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books_authors/1 or /books_authors/1.json
  def destroy
    @books_author.destroy

    respond_to do |format|
      format.html { redirect_to books_authors_url, notice: 'Books author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_books_author
    @books_author = BooksAuthor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def books_author_params
    params.require(:books_author).permit(:book_id, :author_id)
  end
end

app/helpers/books_authors_helper.rb
# frozen_string_literal: true

module BooksAuthorsHelper
end

app/views/books_authors/_books_author.html.erb
<div id="<%= dom_id books_author %>">
  <p>
    <strong>Book:</strong>
    <%= books_author.book_id %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= books_author.author_id %>
  </p>

</div>

app/views/books_authors/_form.html.erb
<%= form_with(model: books_author) do |form| %>
  <% if books_author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(books_author.errors.count, "error") %> prohibited this books_author from being saved:</h2>

      <ul>
        <% books_author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books_authors/edit.html.erb
<h1>Editing books author</h1>

<%= render "form", books_author: @books_author %>

<br>

<div>
  <%= link_to "Show this books author", @books_author %> |
  <%= link_to "Back to books authors", books_authors_path %>
</div>

app/views/books_authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books authors</h1>

<div id="books_authors">
  <% @books_authors.each do |books_author| %>
    <%= render books_author %>
    <p>
      <%= link_to "Show this books author", books_author %>
    </p>
  <% end %>
</div>

<%= link_to "New books author", new_books_author_path %>

app/views/books_authors/new.html.erb
<h1>New books author</h1>

<%= render "form", books_author: @books_author %>

<br>

<div>
  <%= link_to "Back to books authors", books_authors_path %>
</div>

app/views/books_authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @books_author %>

<div>
  <%= link_to "Edit this books author", edit_books_author_path(@books_author) %> |
  <%= link_to "Back to books authors", books_authors_path %>

  <%= button_to "Destroy this books author", @books_author, method: :delete %>
</div>