config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :add_not_null_constraint_to_genres_names
  resources :subscriptions
  resources :subscribs
  resources :subscribtions
  resources :subscribers
  resources :books_authors
  resources :books_genres
  resources :books
  resources :authors
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/books_genre.rb
# frozen_string_literal: true

class BooksGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
  validates :book_id, presence: true
  validates :genre_id, presence: true
  validates :book_id, uniqueness: { scope: :genre_id }
end

app/controllers/books_genres_controller.rb
# frozen_string_literal: true

class BooksGenresController < ApplicationController
  before_action :set_books_genre, only: %i[show edit update destroy]

  # GET /books_genres or /books_genres.json
  def index
    @books_genres = BooksGenre.all
  end

  # GET /books_genres/1 or /books_genres/1.json
  def show; end

  # GET /books_genres/new
  def new
    @books_genre = BooksGenre.new
  end

  # GET /books_genres/1/edit
  def edit; end

  # POST /books_genres or /books_genres.json
  def create
    @books_genre = BooksGenre.new(books_genre_params)

    respond_to do |format|
      if @books_genre.save
        format.html { redirect_to books_genre_url(@books_genre), notice: 'Books genre was successfully created.' }
        format.json { render :show, status: :created, location: @books_genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @books_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books_genres/1 or /books_genres/1.json
  def update
    respond_to do |format|
      if @books_genre.update(books_genre_params)
        format.html { redirect_to books_genre_url(@books_genre), notice: 'Books genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @books_genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @books_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books_genres/1 or /books_genres/1.json
  def destroy
    @books_genre.destroy

    respond_to do |format|
      format.html { redirect_to books_genres_url, notice: 'Books genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_books_genre
    @books_genre = BooksGenre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def books_genre_params
    params.require(:books_genre).permit(:book_id, :genre_id)
  end
end

app/helpers/books_genres_helper.rb
# frozen_string_literal: true

module BooksGenresHelper
end

app/views/books_genres/_books_genre.html.erb
<div id="<%= dom_id books_genre %>">
  <p>
    <strong>Book:</strong>
    <%= books_genre.book_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= books_genre.genre_id %>
  </p>

</div>

app/views/books_genres/_form.html.erb
<%= form_with(model: books_genre) do |form| %>
  <% if books_genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(books_genre.errors.count, "error") %> prohibited this books_genre from being saved:</h2>

      <ul>
        <% books_genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
    <%= form.text_field :genre_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books_genres/edit.html.erb
<h1>Editing books genre</h1>

<%= render "form", books_genre: @books_genre %>

<br>

<div>
  <%= link_to "Show this books genre", @books_genre %> |
  <%= link_to "Back to books genres", books_genres_path %>
</div>

app/views/books_genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books genres</h1>

<div id="books_genres">
  <% @books_genres.each do |books_genre| %>
    <%= render books_genre %>
    <p>
      <%= link_to "Show this books genre", books_genre %>
    </p>
  <% end %>
</div>

<%= link_to "New books genre", new_books_genre_path %>

app/views/books_genres/new.html.erb
<h1>New books genre</h1>

<%= render "form", books_genre: @books_genre %>

<br>

<div>
  <%= link_to "Back to books genres", books_genres_path %>
</div>

app/views/books_genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @books_genre %>

<div>
  <%= link_to "Edit this books genre", edit_books_genre_path(@books_genre) %> |
  <%= link_to "Back to books genres", books_genres_path %>

  <%= button_to "Destroy this books genre", @books_genre, method: :delete %>
</div>