config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :add_not_null_constraint_to_genres_names
  resources :subscriptions
  resources :subscribs
  resources :subscribtions
  resources :subscribers
  resources :books_authors
  resources :books_genres
  resources :books
  resources :authors
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :subscriber
  belongs_to :book
  validates :start, presence: true
  validates :finish, presence: true
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[show edit update destroy]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show; end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit; end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subscription_params
    params.require(:subscription).permit(:subscriber_id, :book_id, :start, :finish, :is_active)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subscriber_id, style: "display: block" %>
    <%= form.text_field :subscriber_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.date_field :start %>
  </div>

  <div>
    <%= form.label :finish, style: "display: block" %>
    <%= form.date_field :finish %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>Subscriber:</strong>
    <%= subscription.subscriber_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= subscription.book_id %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= subscription.start %>
  </p>

  <p>
    <strong>Finish:</strong>
    <%= subscription.finish %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= subscription.is_active %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscriptions</h1>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
  <% end %>
</div>

<%= link_to "New subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>