config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :add_not_null_constraint_to_genres_names
  resources :subscriptions
  resources :subscribs
  resources :subscribtions
  resources :subscribers
  resources :books_authors
  resources :books_genres
  resources :books
  resources :authors
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/subscriber.rb
# frozen_string_literal: true

class Subscriber < ApplicationRecord
  validates :name, presence: { message: 'must be abided' }
end

app/controllers/subscribers_controller.rb
# frozen_string_literal: true

class SubscribersController < ApplicationController
  before_action :set_subscriber, only: %i[show edit update destroy]

  # GET /subscribers or /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1 or /subscribers/1.json
  def show; end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit; end

  # POST /subscribers or /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to subscriber_url(@subscriber), notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1 or /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to subscriber_url(@subscriber), notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1 or /subscribers/1.json
  def destroy
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscriber
    @subscriber = Subscriber.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subscriber_params
    params.require(:subscriber).permit(:name)
  end
end

app/helpers/subscribers_helper.rb
# frozen_string_literal: true

module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_with(model: subscriber) do |form| %>
  <% if subscriber.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
        <% subscriber.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribers/_subscriber.html.erb
<div id="<%= dom_id subscriber %>">
  <p>
    <strong>Name:</strong>
    <%= subscriber.name %>
  </p>

</div>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render "form", subscriber: @subscriber %>

<br>

<div>
  <%= link_to "Show this subscriber", @subscriber %> |
  <%= link_to "Back to subscribers", subscribers_path %>
</div>

app/views/subscribers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscribers</h1>

<div id="subscribers">
  <% @subscribers.each do |subscriber| %>
    <%= render subscriber %>
    <p>
      <%= link_to "Show this subscriber", subscriber %>
    </p>
  <% end %>
</div>

<%= link_to "New subscriber", new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render "form", subscriber: @subscriber %>

<br>

<div>
  <%= link_to "Back to subscribers", subscribers_path %>
</div>

app/views/subscribers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscriber %>

<div>
  <%= link_to "Edit this subscriber", edit_subscriber_path(@subscriber) %> |
  <%= link_to "Back to subscribers", subscribers_path %>

  <%= button_to "Destroy this subscriber", @subscriber, method: :delete %>
</div>